SetEnv SAW_ADMIN_EMAIL admin@ncdd.com
SetEnv SAW_ADMIN_PASSWORD trave11
SetEnv SAW_ADMIN_USER_ID xxxxxxxxxxxxxxxxxxxxx
SetEnv SAW_ADMIN_DISPLAY_NAME Administrator

SetEnv SAW_ADMIN_WEBSITE local.admin.ncdd.com
SetEnv SAW_CONSUMER_WEBSITE local.ncdd.com
SetEnv SAW_CDN http://s.ncdd.com
SetEnv SAW_SSL_CDN https://s3.amazonaws.com/s.ncdd.com

SetEnv SAW_SERVER_NAME web1
SetEnv SAW_SERVER_PUBLIC_NAME web1.local.admin.ncdd.com
SetEnv SAW_SERVER_PUBLIC_URL http://web1.local.admin.ncdd.com
SetEnv SAW_BASE_URL http://local.admin.ncdd.com

SetEnv SAW_FACEBOOK_REDIRECT_URL http://local.admin.ncdd.com/access/facebook

## stripe.com TEST keys: admin@ncdd.com account
SetEnv SAW_STRIPE_PUBLIC_KEY pk_xxxxxxxxxxxxxxxxxxxxxx
SetEnv SAW_STRIPE_SECRET_KEY Ixxxxxxxxxxxxxxxxxxxxxxxxxx
## amazon web services LIVE keys: admin@ncdd.com account
SetEnv SAW_AWS_KEY Axxxxxxxxxxxxxxxxxx
SetEnv SAW_AWS_SECRET Bxxxxxxxxxxxxxxxxxxxxxxx

SetEnv SAW_DATABASE_MONGO_REPLICASET saw
SetEnv SAW_DATABASE_MONGO_DATABASE saw
SetEnv SAW_DATABASE_MONGO_USERNAME
SetEnv SAW_DATABASE_MONGO_PASSWORD
SetEnv SAW_DATABASE_MONGO_SERVERS localhost:27242,localhost:27243,localhost:27244
SetEnv SAW_DATABASE_MONGO_SAFE 0
SetEnv SAW_DATABASE_MONGO_FSYNC 0

SetEnv SAW_SESSION_NAME ncddsessid
SetEnv SAW_SESSION_COOKIE_SECURE false
SetEnv SAW_SESSION_COOKIE_HTTPONLY false
SetEnv SAW_SESSION_COOKIE_DOMAIN .ncdd.com
SetEnv SAW_SESSION_COOKIE_PATH /
SetEnv SAW_SESSION_COOKIE_LIFETIME 15552000
SetEnv SAW_SESSION_CACHE_LIMITER nocache
SetEnv SAW_SESSION_DATABASE_MONGO_REPLICASET saw
SetEnv SAW_SESSION_DATABASE_MONGO_DATABASE saw
SetEnv SAW_SESSION_DATABASE_MONGO_COLLECTION session
SetEnv SAW_SESSION_DATABASE_MONGO_USERNAME
SetEnv SAW_SESSION_DATABASE_MONGO_PASSWORD
SetEnv SAW_SESSION_DATABASE_MONGO_SERVERS localhost:27242,localhost:27243,localhost:27244
SetEnv SAW_SESSION_DATABASE_MONGO_SAFE 0
SetEnv SAW_SESSION_DATABASE_MONGO_FSYNC 0

SetEnv SAW_MAILER_HOST smtp.gmail.com
SetEnv SAW_MAILER_PORT 465
SetEnv SAW_MAILER_USERNAME no-reply@kinollc.com
SetEnv SAW_MAILER_PASSWORD noreply400
SetEnv SAW_MAILER_ENCRYPTION ssl
SetEnv SAW_MAILER_FROM support@ncdd.com
SetEnv SAW_MAILER_FROM_NAME "ncdd.com Support"
SetEnv SAW_MAILER_BCC_TO parallel32@gmail.com
SetEnv SAW_ERROR_LOG_MAILER_TO parallel32@gmail.com
SetEnv SAW_ERROR_LOG_MAILER_FROM server@ncdd.com

SetEnv SAW_FILE_UPLOAD_DIR /var/www/upload