SetEnv SAW_ADMIN_EMAIL parallel32@gmail.com
SetEnv SAW_ADMIN_PASSWORD ncdd400
SetEnv SAW_ADMIN_USER_ID xxxxxxxxxxxxxxxxxxxxx
SetEnv SAW_ADMIN_DISPLAY_NAME Administrator

SetEnv SAW_ADMIN_WEBSITE admin.ncdd.com
SetEnv SAW_CONSUMER_WEBSITE ncdd.com
SetEnv SAW_PUBLIC_CDN http://public.ncdd.netdna-cdn.com
SetEnv SAW_PUBLIC_SSL_CDN https://public-ncdd.netdna-ssl.com
SetEnv SAW_CDN http://admin.ncdd.netdna-cdn.com
SetEnv SAW_SSL_CDN https://admin-ncdd.netdna-ssl.com

SetEnv SAW_SERVER_NAME web1
SetEnv SAW_SERVER_PUBLIC_NAME admin.ncdd.com
SetEnv SAW_SERVER_PUBLIC_URL http://admin.ncdd.com
SetEnv SAW_BASE_URL http://admin.ncdd.com

## NCDDNews twitter app
SetEnv TWITTER_CONSUMER_KEY ChX6fitJ7Qn6Ek1ZREjlHQeD8
SetEnv TWITTER_CONSUMER_SECRET kWg3wcosP2ZxzWUUrgLF8oTgBfEY5xUlyTMHenKOvGmtnbNj12
SetEnv TWITTER_ACCESS_TOKEN 1092704977-PjivOVi8HZeIh4dUvq10gTAwF8DuQjImGiuOo8Z
SetEnv TWITTER_ACCESS_TOKEN_SECRET 57whI52HwyvqkEhU2GHsY8i9YVZltXktCG3TGjGpzb033

SetEnv SAW_FACEBOOK_REDIRECT_URL http://admin.ncdd.com/access/facebook

## stripe.com TEST keys: admin@ncdd.com account
SetEnv SAW_STRIPE_PUBLIC_KEY pk_live_ILTIFT1CTadkr2nYsz8kyYt4
SetEnv SAW_STRIPE_SECRET_KEY sk_live_xwQaiDO0jVY3y5lALURqU1Na
## amazon web services LIVE keys: admin@ncdd.com account
SetEnv SAW_AWS_KEY Axxxxxxxxxxxxxxxxxx
SetEnv SAW_AWS_SECRET Bxxxxxxxxxxxxxxxxxxxxxxx

SetEnv SAW_DATABASE_MONGO_REPLICASET saw
SetEnv SAW_DATABASE_MONGO_DATABASE ncdd
SetEnv SAW_DATABASE_MONGO_USERNAME
SetEnv SAW_DATABASE_MONGO_PASSWORD
SetEnv SAW_DATABASE_MONGO_SERVERS localhost:27242
SetEnv SAW_DATABASE_MONGO_SAFE 0
SetEnv SAW_DATABASE_MONGO_FSYNC 0

SetEnv SAW_SESSION_NAME ncddsessid
SetEnv SAW_SESSION_COOKIE_SECURE false
SetEnv SAW_SESSION_COOKIE_HTTPONLY false
SetEnv SAW_SESSION_COOKIE_DOMAIN .ncdd.com
SetEnv SAW_SESSION_COOKIE_PATH /
SetEnv SAW_SESSION_COOKIE_LIFETIME 15552000
SetEnv SAW_SESSION_CACHE_LIMITER nocache
SetEnv SAW_SESSION_DATABASE_MONGO_REPLICASET saw
SetEnv SAW_SESSION_DATABASE_MONGO_DATABASE ncdd
SetEnv SAW_SESSION_DATABASE_MONGO_COLLECTION session
SetEnv SAW_SESSION_DATABASE_MONGO_USERNAME
SetEnv SAW_SESSION_DATABASE_MONGO_PASSWORD
SetEnv SAW_SESSION_DATABASE_MONGO_SERVERS localhost:27242
SetEnv SAW_SESSION_DATABASE_MONGO_SAFE 0
SetEnv SAW_SESSION_DATABASE_MONGO_FSYNC 0

SetEnv SAW_MAILER_HOST smtp.gmail.com
SetEnv SAW_MAILER_PORT 465
SetEnv SAW_MAILER_USERNAME support@ncdd.com
SetEnv SAW_MAILER_PASSWORD terf6ilk
SetEnv SAW_MAILER_ENCRYPTION ssl
SetEnv SAW_MAILER_FROM support@ncdd.com
SetEnv SAW_MAILER_FROM_NAME "ncdd.com Support"
SetEnv SAW_MAILER_BCC_TO parallel32@gmail.com
SetEnv SAW_ERROR_LOG_MAILER_TO parallel32@gmail.com
SetEnv SAW_ERROR_LOG_MAILER_FROM support@ncdd.com

SetEnv SAW_FILE_UPLOAD_DIR /var/www/upload