<?php
define("SAW_SESSION_COOKIE_SECURE",getenv('SAW_SESSION_COOKIE_SECURE'));
define("SAW_SESSION_COOKIE_HTTPONLY",getenv('SAW_SESSION_COOKIE_HTTPONLY'));
define("SAW_SESSION_COOKIE_PATH",getenv('SAW_SESSION_COOKIE_PATH'));
define("SAW_SESSION_COOKIE_LIFETIME",getenv('SAW_SESSION_COOKIE_LIFETIME'));

define("SAW_SESSION_DATABASE_MONGO_REPLICASET",getenv('SAW_SESSION_DATABASE_MONGO_REPLICASET'));
define("SAW_SESSION_DATABASE_MONGO_DATABASE",getenv('SAW_SESSION_DATABASE_MONGO_DATABASE'));
define("SAW_SESSION_DATABASE_MONGO_COLLECTION",getenv('SAW_SESSION_DATABASE_MONGO_COLLECTION'));
define("SAW_SESSION_DATABASE_MONGO_USERNAME",getenv('SAW_SESSION_DATABASE_MONGO_USERNAME'));
define("SAW_SESSION_DATABASE_MONGO_PASSWORD",getenv('SAW_SESSION_DATABASE_MONGO_PASSWORD'));
define("SAW_SESSION_DATABASE_MONGO_SERVERS",getenv('SAW_SESSION_DATABASE_MONGO_SERVERS'));
define("SAW_SESSION_DATABASE_MONGO_SAFE",(int)getenv('SAW_SESSION_DATABASE_MONGO_SAFE'));
define("SAW_SESSION_DATABASE_MONGO_FSYNC",(int)getenv('SAW_SESSION_DATABASE_MONGO_FSYNC'));